### PR TITLE
Wag. Use simple JSON for datastore.

### PR DESCRIPTION
**Pull request by nathanleiby**
**Jira:** [INFRA-1124](https://clever.atlassian.net/browse/INFRA-1124)

**Overview:**

Re-writes who is who so that it (1) uses Wag (2) is backed by JSON (read from a local file or S3).
The JSON or S3 is only read in on application start, so modifying it would mean modifying the file and then redeploying.

**Testing:**

Local testing.

**Roll Out:**

Test this with services that already depend on who is who.

### CODE REVIEW

**Comment by nathanleiby** [comment]
Needs a little more refactoring of Dockerfile run command in order to pass in path to S3 file

**Comment by nathanleiby** [comment]
No rush to merge this at all. Will wait to discuss with @xavi- to see if this is the preferred approach or he has a very different vision.

**Comment by mohit** [comment]
🙀

**Comment by kvigen** [comment]
👏

**Comment by nathanleiby** [comment]
Closing, since it seems like we're not using this change / will move to who-is-who-too cc @xavi-

**Pull request closed without merging**
